intel/neural-speed

requirements.txt

update requirement for python build binary

update requirement for python build binary

---

docker/DockerFile
docker/READEME.md

Add docker file for end-users to build docker images

add docker file and readme

---

neural_speed/application/main_pybind.cpp

Fix pybind compile

---

.github/workflows/scripts/install_binary.sh
.github/workflows/unit-test-llmruntime.yml
.github/workflows/unitTest/env_setup.sh
.github/workflows/unitTest/unittest_llmruntime.sh
developer_document.md
tests/test_python_api.py

test of python api

---

neural_speed/convert/convert_quantized_llama.py
neural_speed/convert/convert_quantized_mistral.py

We support when hugging face models' config.json have rope_scaling: null scene

Support the awq convert when rope scale is null

---

docs/supported_models.md

documentation
add AWQ in supported list
n/a
n/a
n/a

add AWQ in supported list

---

neural_speed/models/requirements/common.txt

Update common.txt for GGUF
Update common.txt for GGUF
N/A
Manually
Update common.txt for GGUF

Update common.txt for GGUF

---

neural_speed/convert/convert_chatglm.py

Bug fix.
Fixed the chatglm convert issue.
N/A
CI
N/A

Fixed the chatglm convert issue.

---

neural_speed/models/llama/llama.h
neural_speed/models/qwen/qwen.h

add scratch memory for mistral&qwen

---

README.md

documentation 
refine doc
n/a
n/a
n/a

refine doc

---

bestla/bestla/bestla_device.h

[Bestla] Fix for hybrid

---

bestla/bestla/kernel_avx2.h
bestla/bestla/kernel_avx512f.h
bestla/bestla/ut/bestla_prologue_b.cpp

fix BesTLA compile on Windows

---

CMakeLists.txt
README.md
neural_speed/application/main_run.cpp
neural_speed/models/llama/llama.cpp
neural_speed/models/model_utils/model_utils.cpp
neural_speed/models/model_utils/model_utils.h

fix ns log perf problem

---

neural_speed/application/main_run.cpp
neural_speed/models/llama/llama.cpp

uncomment print codes

---

neural_speed/__init__.py
neural_speed/application/main_pybind.cpp
neural_speed/convert/common.py

https://github.com/intel/neural-speed/issues/77
Issues: xxx

update qwen python api

---

neural_speed/__init__.py
scripts/cal_diff.py
scripts/perplexity.py
tests/test_python_api.py

bug fix 
migrate pr: https://github.com/intel/intel-extension-for-transformers/pull/818
Issues: xxx

load processed model automatically

---

neural_speed/models/qwen/qwen.h

not
enable qwen-1.8b
Issues: xxx

enable qwen-1.8b

---

README.md
neural_speed/convert/convert_baichuan.py
neural_speed/convert/convert_chatglm.py
neural_speed/convert/convert_llama.py

New Features
[LLM Runtime] Support loadding chatglm1&2 & baichuan from HF directly.
N/A
Manually
N/A

[LLM Runtime] Support loadding models from HF directly.

---

docs/supported_models.md
neural_speed/core/ne_layers.c
setup.py

A32543254 patch 4

---

neural_speed/__init__.py
neural_speed/convert/__init__.py
neural_speed/convert/common.py
neural_speed/convert/convert_quantized_gptj.py
neural_speed/convert/convert_quantized_llama.py
scripts/cal_acc.py
scripts/convert.py
scripts/huggingface.py

usage:
```
python scripts/convert.py ~/models/gptq/Llama-2-7B-Chat-GPTQ/ --outfile llama.gptq.bin --use_quantized_model
```
awq/gptq/autoround is decided in config.json->quant_method

add autoround and remove name in path

---

include/experimental/group/gemm/impl/int4_dequantize_xmx_xe.hpp
include/subgroup/tile/impl/prefetch_xe.hpp
tests/integration/data_transformer/main.cpp
tests/integration/gemm/bf16_stream_k/main.cpp
tests/integration/softmax/softmax_bwd.cpp
tests/integration/softmax/softmax_fwd.cpp
tests/unit/tile_load_store/kernel_func.hpp
tests/utils/execution.hpp

as title.
https://github.com/intel/neural-speed/pull/128 creates some warnings on Linux build.

fix compile errors on Linux

---

neural_speed/convert/common.py
neural_speed/convert/convert_quantized_llama.py
neural_speed/convert/convert_quantized_mistral.py
neural_speed/models/qwen/qwen_utils.cpp

Bug Fixed.
* Fixed Qwen loading 
* Fixed Mistral GPTQ convert
related PR: https://github.com/intel/neural-speed/pull/127 https://github.com/intel/neural-speed/pull/101
Qwen Inference screenshot:
N/A
Manually
N/A

[Bug Fix] Fixed Qwen loading & Mistral GPTQ convert

---

neural_speed/convert/convert-hf-to-gguf.py

Bug fixed.
[Bug Fixed] Fixed the GGUF convert issue
N/A
Manually
N/A

[Bug Fixed] Fixed the GGUF convert issue

---

CMakeLists.txt
include/common/core/common.hpp
include/experimental/group/gemm/compute_policy.hpp
include/experimental/group/gemm/impl/int4_dequantize_xmx_xe.hpp
include/group/gemm/compute_policy.hpp
include/group/gemm/impl/default_fpu_xe.hpp
include/kernel/gemm/impl/kslicing_xe.hpp
include/kernel/gemm/impl/stream_k_xe.hpp
include/subgroup/tile/impl/load_xe.hpp
include/subgroup/tile/impl/payload_xe.hpp
tests/integration/gemm/fp32/CMakeLists.txt
tests/integration/gemm/fp32/main_dg2.cpp
tests/integration/gemm/int4_dequantization_bias/main_dg2.cpp

Xetla mtl zhe

---

bestla/bestla/bestla_utils.h
bestla/bestla/kernel_jit_injector.h
neural_speed/convert/common.py
neural_speed/convert/convert_quantized_gptj.py
neural_speed/convert/convert_quantized_llama.py
neural_speed/convert/convert_quantized_mistral.py
neural_speed/convert/convert_quantized_mixtral.py
neural_speed/convert/convert_quantized_qwen.py

[GPT-Q] Fix Autoround acc regression

---

neural_speed/convert/convert-hf-to-gguf.py
neural_speed/convert/convert_bloom.py
neural_speed/convert/convert_dolly.py
neural_speed/convert/convert_gptj.py
neural_speed/convert/convert_gptneox.py
neural_speed/convert/convert_opt.py
neural_speed/convert/convert_phi.py
neural_speed/convert/convert_quantized_bloom.py
neural_speed/convert/convert_quantized_qwen.py
neural_speed/convert/convert_qwen.py
neural_speed/convert/convert_starcoder.py
neural_speed/convert/convert_whisper.py
neural_speed/models/qwen/qwen_utils.cpp

not
bug fix
add trust_remote_code=True in model convert
[Issues161](https://github.com/intel/neural-speed/issues/161)

fix qwen load error

---

neural_speed/convert/convert_baichuan.py
neural_speed/models/baichuan/baichuan.cpp
neural_speed/models/baichuan/baichuan.h
neural_speed/models/baichuan/baichuan_utils.cpp
neural_speed/models/model_utils/model_files.h

Bug fixed.
Feature Enhence.
Refactor Baichuan13B architecture to pave the way for the GGUF format & Baichuan7B.
But still need some extra effort for the Baichuan7B accuracy.
N/A
Baichuan13B screenshot:
N/A

[Model Enhence] Add Baichuan-7B architecutre and refactor Baichuan-13B.

---

bestla/bestla/kernel_avx2.h
neural_speed/core/layers/mha_dense.cpp

Fix bug
exp in MHA will overflow in some case.

mha enhance

---

docs/supported_models.md

Fix supported_models.md format

---

neural_speed/models/requirements/baichuan13b-gptq.sh
neural_speed/models/requirements/baichuan13b-gptq.txt
neural_speed/models/requirements/mistral.sh
neural_speed/models/requirements/mistral.txt
neural_speed/models/requirements/mixtral-gptq.sh
neural_speed/models/requirements/mixtral-gptq.txt
tests/model-test/cpp_graph_inference.sh

Bug fixed.
rename requirements of extension tests from txt to sh
N/A
N/A

rename requirements of extension tests from txt to sh

---

neural_speed/convert/convert_chatglm.py

Bug Fixed
* Remove import pdb
* Fixed convert issues for chatglm.
Error screenshots:
N/A
[neural_speed_extension #105 [Jenkins] (intel.com)](https://inteltf-jenk.sh.intel.com/job/neural_speed_extension/105/)
N/A

[Bug Fix] Fixed convert issues for ChatGLM.

---

README.md

[Doc] Refine README

---

neural_speed/convert/convert_llama.py
requirements.txt

not
fix ci convert llama zip error

fix ci convert llama zip error

---

neural_speed/convert/common.py
requirements.txt

Issues: xxx
`python neural_speed/convert/convert_quantized_mistral.py --outfile test.bin Intel/neural-chat-7b-v3-3-int4-inc`

[GPT-Q] Load mode from HF HUB

---

neural_speed/models/model_utils/model_utils.cpp

[Neural Speed] Fix MHA KV Cache Seq Cpy

---

.github/workflows/unit-test-bestla.yml

recover bestla ut

---

.github/workflows/cpp-graph-test.yml
.github/workflows/unit-test-bestla.yml

update scripts for ut and model test

---

setup.py

Update setup.py for windows build  on 64 bit compiler

---

docs/prompt_template.md
docs/supported_models.md
neural_speed/convert/convert-hf-to-gguf.py
neural_speed/convert/convert_baichuan.py
neural_speed/models/baichuan/baichuan.cpp

Supported Baichuan2-7B.
N/A
N/A

[Model Enabling] Baichuan2-7B Enabling

---

neural_speed/__init__.py

not
enable whisper init from bin

enable init whisper from bin

---

neural_speed/__init__.py
neural_speed/application/main_pybind.cpp
neural_speed/models/llama/llama_utils.cpp

[Neural Speed] Reload if `ctx_size` changes and add `reset_kv_cache` API

---

scripts/huggingface.py

fix cal_acc error when use autoround

---

include/common/core/arch_config.hpp
include/common/core/base_types.hpp
include/common/core/common.hpp
include/common/core/common_types.hpp
include/experimental/common/common.hpp
include/group/gemm/impl/default_xmx_xe.hpp
include/group/gemm/impl/unaligned_xmx_xe.hpp
include/subgroup/tile/impl/load_xe.hpp
include/subgroup/tile/impl/mma_xe.hpp
include/subgroup/tile/impl/store_xe.hpp
include/xetla_common_types.hpp

@DDEle @wanzizhu @JianpingChen066

[XeTLA] align with IPEX master bac2d0d

---

neural_speed/convert/__init__.py
setup.py

Update setup.py for install

---

bestla/bestla/bestla_wrapper.h
bestla/bestla/ut/bestla_benchmark.cpp
bestla/bestla/ut/kernel_wrapper.cpp

[BesTLA] Support other output dtypes of GEMV's epilgoue 

---

neural_speed/core/README.md

Update int2&int3 doc

---

README.md

Issues: xxx
fix  https://github.com/intel/neural-speed/issues/237

[DOC] Add `Neural_Speed` Usage in `Neural Chat` Server in `README.md` 

---

neural_speed/__init__.py
scripts/cal_acc.py
scripts/perplexity.py
tests/test_model_server.py

1. Reuse f32.bin file for other quantization types. Add clear flag to delete the whole tmp folder
2. Fix perplexity.py file
3. add scale dtype and alg to model name

[Python] Fix some py test scripts error

---

.github/workflows/Scaner_BDBA.yml
.github/workflows/Scaner_Trivil.yml
.github/workflows/format_scan.yml
.github/workflows/scripts/formatScan/hadolint.sh
.github/workflows/scripts/formatScan/trellix.sh
.github/workflows/trellix.yml
.github/workflows/windows-test.yml

add more security scan for SDL

add more security scan

---

README.md
docs/gguf.md

align with HF api https://huggingface.co/docs/transformers/en/gguf
Issues: xxx

align gguf_file with HF api

---

neural_speed/__init__.py

add tinyllama

---

docs/continuous_batching.md

[DOC ] Fix cont-batching doc

---

.github/workflows/scripts/prepare_env_with_conda.bat
.github/workflows/windows-test.yml

[CI]fix windows proxy error

---

.github/workflows/scripts/models/cpp_graph_inference.sh
neural_speed/models/llama/llama.h
neural_speed/models/qwen/qwen.h

add [codestral-22b](https://huggingface.co/mistralai/Codestral-22B-v0.1)

[model]add codestral-22b

---

.github/workflows/cpp-graph-test.yml
.github/workflows/scripts/models/calculate_percertiles.py
neural_speed/models/bloom/bloom.cpp
neural_speed/models/bloom/bloom_utils.cpp

Enable bloom mha fusion
Q4j32 Result

[Fusion]enable bloom mha fusion

---

neural_speed/convert/convert_quantized_qwen.py
neural_speed/convert/convert_qwen.py
scripts/huggingface.py

fix qwen convert error

---

neural_speed/convert/convert_chatglm.py

[Bug]fix glm4 acc error

---

.github/workflows/scripts/models/cpp_graph_inference.sh
.github/workflows/scripts/prepare_env_with_conda.sh
.github/workflows/unit-test-bestla.yml
neural_speed/__init__.py
tests/model-test/cpp_graph_inference.sh

[CI]update miniforge

---

CMakeLists.txt
include/experimental/group/gemm/compute_policy.hpp
include/subgroup/tile/impl/load_xe.hpp
include/subgroup/tile/impl/payload_xe.hpp

XeTLA Fix Column Major Bugs

---

include/common/core/memory.hpp

Originally as part of #309
OneAPI 2024.2 introduced the following changes compared with OneAPI 2024.1
- small ESIMD memory API changes
- introduce pvc_vg/mtl/lnl/arl/bmg in `device_architecture`
N/A
IPEX internal tests
N/A

XeTLA Fix load/store 1D

---

include/common/core/common.hpp
include/common/core/math_mma.hpp
include/common/core/memory.hpp
include/experimental/group/gemm/impl/int4_dequantize_xe.hpp
include/experimental/kernel/col_major_shuf/col_major_shuf_xe.hpp
include/group/epilogue/impl/stream_k_op_xe.hpp
include/group/global_reduction.hpp
include/subgroup/tile/common.hpp
include/subgroup/tile/impl/load_xe.hpp
include/subgroup/tile/impl/payload_xe.hpp
include/subgroup/tile/impl/prefetch_xe.hpp
include/subgroup/tile/impl/store_xe.hpp
tests/integration/gemv/int4/main.cpp
tests/integration/vector_add/int32_1d/kernel_func.hpp
tests/integration/vector_add/tf32_1d/kernel_func.hpp
tests/unit/global_atomic/kernel_func.hpp
tests/unit/global_load_store/kernel_func.hpp
tests/unit/local_load_store/kernel_func.hpp
tests/unit/math_general/kernel_func.hpp
tests/unit/named_barrier/kernel_func.hpp
tests/unit/raw_send/kernel_func.hpp

Sync ipex(modify prefetch)

---

include/subgroup/tile/impl/load_xe.hpp

As title
N/A
Internal IPEX CI 
No

Revert max_load_vec_elems
