bestla/jblas/jit_blas.h
bestla/jblas/jit_blas_device.h
bestla/jblas/jit_blas_prologue_a.h
bestla/jblas/jit_blas_prologue_b.h
bestla/jblas/jit_blas_storage.h
bestla/jblas/kernel_avx512f.h
bestla/jblas/ut/jit_blas_prologue_b.cpp
bestla/jblas/ut/jit_blas_ut.h
neural_speed/core/layers/inner_product.cpp
neural_speed/core/layers/ip_fusion_ffn.cpp
neural_speed/core/layers/ip_fusion_qkv.cpp
neural_speed/core/layers/jblas_defs.h
neural_speed/core/layers/jblas_gemm.cpp
neural_speed/core/layers/mha_dense.cpp
neural_speed/core/layers/ne_jblas.cpp

Replace WeightKBlockF4 and WeightKBlockF8 with WeightKBlockNFloat.
Update PE core cache optimization.

Sync jblas

---

neural_speed/application/main_run.cpp

1. fix the bug of default value -1 of n_predict.
2. enable warmup when printing timings.

Fix warmup prompt length and add ns_log_level control

---

bestla/CMakeLists.txt
bestla/bestla/bestla_device.h
neural_speed/models/model_utils/gguf.h

1. remove compiler options and link options of bestla:
a. passing our compile_option to external projects is not expected by their maintainers.
b. target_link_options which enlarges the stack size is not a good choice. If the threads are created by another bin file, the stack size of each thread won't be changed.
2. fix compile errors on Windows:
a. designator of initializer is not supported in MSVC when compiling cpp files, which is officially a C99 feature.

Remove options from bestla& fix error of MSVC

---

.github/workflows/cpp-graph-test.yml
.github/workflows/unit-test-bestla.yml
bestla/CMakeLists.txt
bestla/bestla/ut/bestla_ut.h
bestla/bestla/ut/kernel_wrapper.cpp

add CI for bestla, add SPR nodes for UT

add tests and nodes

---

scripts/inference.py
scripts/quantize.py
scripts/run.py

Bug fixed.
* Fixed tokenizer issues of straightforward APIs. (Only Qwen & Baichuan will be affected)
* Fixed the quantize & inference path of one-click run.
N/A
Manually
N/A

[LLM Runtime]Fixed straightforward-API issues

---

scripts/inference.py
scripts/quantize.py

- Fix a blocker that prevents Neural Speed from running on Windows platforms.
- In your code, you look for the binary if it's a windows, but there is none since in the README we build Neural Speed with setup.py, and not with cmake anymore, so in any case whether it's Linux or Windows we are going to use the executable that can be found in the Neural Speed package.
- Completes the conversion, quantization and inference successfully.
- Tested on my SPR workstation with Win11 OS, and it's working as expected.
N/A

[Neural Speed] Fix a blocker on Windows platforms

---

neural_speed/core/ne_layers.c
setup.py

when NS_PROFILING is OFF and NEURAL_SPEED_VERBOSE=0/2, will print warning instead of 0ms logs
`[Warning] To collect profiling data, please recompile with NS_PROFILING=ON.`

update profling log when NS_PROFILING is OFF

---

docs/supported_models.md
neural_speed/convert/common.py
neural_speed/convert/convert_llama.py
neural_speed/convert/convert_quantized_llama.py
neural_speed/models/llama/llama.h

Support gptq with solar

---

neural_speed/__init__.py
scripts/whisper_example.py

not
fix whisper python api
Issues: [issue104](https://github.com/intel/neural-speed/issues/104)
no

add whisper example

---

CMakeLists.txt
bestla/bestla/ut/kernel_wrapper.cpp

1. set OMP on  for bestla. 
2. Check AVX512F flag for LayerNormalization.
Perf on Ultra7-155H, Mistral-7B int4, group=-1, compute_dtype=int8
```
Once we have made our plans,
We can’t follow them.
model_print_timings:        load time =   100.93 ms
model_print_timings:      sample time =     8.00 ms /    16 runs   (    0.50 ms per token)
model_print_timings: prompt eval time =   100.82 ms /     2 tokens (   50.41 ms per token)
model_print_timings:        eval time =  1239.00 ms /    15 runs   (   82.60 ms per token)
model_print_timings:       total time =  1355.56 ms
========== eval time log of each prediction ==========
prediction   0, time: 100.82ms
prediction   1, time: 79.96ms
prediction   2, time: 81.61ms
prediction   3, time: 80.69ms
prediction   4, time: 81.98ms
prediction   5, …
```

check isa for UT, use OMP as default

---

neural_speed/core/ne_layers.c
neural_speed/core/ne_layers.h

Add new API for YaRN rop-scale:
NE_API struct ne_tensor* ne_rope_custom_inplace(struct ne_context* ctx, struct ne_tensor* a, int n_past, int n_dims, int mode,
int prompt_size, float freq_base, float freq_scale,
int yarn_orig_ctx, float ext_factor, float attn_factor,
float beta_fast, float beta_slow);
// shift all tokens by a give p (n_shift)
// Optionally give a 1d tensor of precomputed interleaved cos/sin value of n_shift*scale^k for k \in [0, n_dims)
NE_API struct ne_tensor* ne_rope_custom_shift_inplace(struct ne_context* ctx, struct ne_tensor* a, int n_shift, int n_dims,
int mode, int prompt_size, int n_keep, struct ne_tensor* cossin,
float freq_base, float freq_scale,
int yarn_orig_ctx, float ext_factor, float attn_factor,
float beta_fast, float beta_slow);
Change ne_layer internal …

Implement the YaRN rop scaling feature

---

.github/workflows/cpp-graph-test.yml
.github/workflows/format_scan.yml
.github/workflows/scripts/formatScan/clangtidy.sh
.github/workflows/unit-test-llmruntime.yml
.gitignore
CMakeLists.txt

issues introduced in https://github.com/intel/neural-speed/pull/121

fix clang-tidy issues

---

neural_speed/convert/convert_llama.py
neural_speed/convert/convert_mistral.py

New Feature.
Related PR: https://github.com/intel/neural-speed/pull/93
[Enhence] Add the feature of Mistral online loading from the HF
validated models:
* Intel/neural-chat-7b-v3-1
* [mistralai/Mistral-7B-v0.1 · Hugging Face](https://huggingface.co/mistralai/Mistral-7B-v0.1)
```python
from transformers import AutoTokenizer, TextStreamer
from intel_extension_for_transformers.transformers import AutoModelForCausalLM
model_name = "Intel/neural-chat-7b-v3-1"     # Hugging Face model_id or local model
#model_name = "/home/zhenzhong/model/neural-chat-7b-v3-1"
prompt = "Once upon a time, there existed a little girl,"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
inputs = tokenizer(prompt, return_tensors="pt").input_ids
streamer = TextStreamer(tokenizer)
model = …
```

[Enhence] Add the feature of Mistral online loading from the HF

---

neural_speed/convert/convert_baichuan.py
neural_speed/convert/convert_bloom.py
neural_speed/convert/convert_chatglm.py
neural_speed/convert/convert_falcon.py
neural_speed/convert/convert_gptj.py
neural_speed/convert/convert_gptneox.py
neural_speed/convert/convert_llama.py
neural_speed/convert/convert_mistral.py
neural_speed/convert/convert_mpt.py
neural_speed/convert/convert_opt.py
neural_speed/convert/convert_qwen.py
neural_speed/convert/convert_starcoder.py
neural_speed/models/model_utils/model_files.h
neural_speed/models/model_utils/model_types.h

1. Add  YaRN rope scaling data structure and conversion read/write of the yarn parameters
convert data model and read/quant the mode correctly.
No.

Yarn feature

---

CMakeLists.txt
neural_speed/application/audio_run.cpp
neural_speed/application/common.cpp
neural_speed/application/main_pybind.cpp
neural_speed/application/main_run.cpp
neural_speed/application/pybind_gptj.cpp
neural_speed/application/whisper_pybind.cpp
neural_speed/cmake/Common.cmake
neural_speed/core/ne_layers.c
neural_speed/models/baichuan/baichuan_utils.cpp
neural_speed/models/model_utils/arg_parse.cpp
neural_speed/models/model_utils/model_files.h
neural_speed/models/model_utils/model_utils.cpp
neural_speed/models/model_utils/model_utils.h
neural_speed/models/model_utils/quant_utils.cpp
neural_speed/models/model_utils/scheduler.cpp
neural_speed/vectors/cpu/quantize.h
requirements.txt
scripts/perplexity.py
setup.py

- Avoid most of warnings when compiling with MSVC (https://github.com/intel/neural-speed/actions/runs/7998735186/job/21845460790#step:3:959)
- Resolve lto warnings on Linux
- Include missing pyd files
- PPL supports readding cnn_dailymail
- Using /utf-8 on Windows
(actually they are non-mha changes on the mha-avx2 branch)
No

Improvements Targeting Windows

---

docs/gptq_and_awq.md
docs/supported_models.md
neural_speed/convert/convert_quantized_gptj.py
neural_speed/convert/convert_quantized_llama.py
scripts/python_api_example.py

* GPTQ & AWQ models validation
* Bug Fixed: Fixed the convert issue caused by #97
* Doc Refine: Refine related to GPTQ &AWQ docs for release 1.3.2
Validated GPTQ & AWQ models directly from the HuggingFace:
* [Llama-2-7B-Chat-GPT](https://huggingface.co/TheBloke/Llama-2-7B-Chat-GPTQ) & [Llama-2-13B-Chat-GPT](https://huggingface.co/TheBloke/Llama-2-7B-Chat-GPTQ)
* [CodeLlama-7B-Instruct-GPTQ](https://huggingface.co/TheBloke/CodeLlama-7B-Instruct-GPTQ) & [CodeLlama-13B-Instruct-GPTQ](https://huggingface.co/TheBloke/CodeLlama-13B-Instruct-GPTQ)
* [SOLAR-10.7B-v1.0-GPTQ](https://huggingface.co/TheBloke/SOLAR-10.7B-v1.0-GPTQ)
* [Llama-2-7B-AWQ](https://huggingface.co/TheBloke/Llama-2-7B-AWQ) & [Llama-2-13B-chat-AWQ](https://huggingface.co/TheBloke/Llama-2-13B-chat-AWQ)
* …

[GPTQ Enhence] Refined Doc & Fixed GPTQ & AWQ issues.

---

neural_speed/core/ne_layers.c
neural_speed/core/ne_layers.h

Resubmit "Implement the YaRN rop scaling feature (#109)"
This reverts commit 2e94db215e581697fd9d79b808d907cc1d03b1fc.
Do not find issues, Could not reproduce issues. 
Resubmit yarn with by recover the previous submit.
Implement the YaRN feature.
Add two new API for YaRN rop-scale:
NE_API struct ne_tensor* ne_rope_custom_inplace(struct ne_context* ctx, struct ne_tensor* a, int n_past, int n_dims, int mode,
int prompt_size, float freq_base, float freq_scale,  int yarn_orig_ctx, float ext_factor, float attn_factor,
float beta_fast, float beta_slow);
NE_API struct ne_tensor ne_rope_custom_shift_inplace(struct ne_context* ctx, struct ne_tensor* a, int n_shift, int n_dims,
int mode, int prompt_size, int n_keep, struct ne_tensor* cossin,
float freq_base, float freq_scale, int yarn_orig_ctx, …

Revert "Revert "Implement the YaRN rop scaling feature (#109)""

---

neural_speed/convert/convert_chatglm.py
neural_speed/models/chatglm/chatglm2.cpp
neural_speed/models/chatglm/chatglm2.h
neural_speed/models/chatglm/chatglm2_utils.cpp
neural_speed/models/model_utils/model_types.h
tests/model-test/cpp_graph_inference.sh

New feature
Support FFN_fusion for the ChatGLM2
perf

[FFN Fusion] Support FFN_fusion for the ChatGLM2

---

neural_speed/convert/convert_mistral.py
neural_speed/convert/convert_quantized_gptj.py
neural_speed/convert/convert_quantized_mistral.py

Feature Add
Related PR: https://github.com/intel/neural-speed/pull/140
* [Mistral-7B-Instruct-v0.1-GPTQ](https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GPTQ)
* [Mistral-7B-Instruct-v0.2-GPTQ](https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GPTQ)
N/A
Manually
N/A

[GPTQ Enhence] Support Mistral-GPTQ 

---

neural_speed/core/ne_layers.c
neural_speed/core/ne_layers.h

Resubmit "Implement the YaRN rop scaling feature (https://github.com/intel/neural-speed/pull/109)"
Fix Windows build error.
Implement the YaRN feature.
Add two new API for YaRN rop-scale:
NE_API struct ne_tensor* ne_rope_custom_inplace(struct ne_context* ctx, struct ne_tensor* a, int n_past, int n_dims, int mode,
int prompt_size, float freq_base, float freq_scale, int yarn_orig_ctx, float ext_factor, float attn_factor,
float beta_fast, float beta_slow);
NE_API struct ne_tensor ne_rope_custom_shift_inplace(struct ne_context* ctx, struct ne_tensor* a, int n_shift, int n_dims,
int mode, int prompt_size, int n_keep, struct ne_tensor* cossin,
float freq_base, float freq_scale, int yarn_orig_ctx, float ext_factor, float attn_factor,
float beta_fast, float beta_slow);
Change ne_layer internal …

resubmit "Implement the YaRN rop scaling feature"

---

bestla/bestla/bestla_gemm.h

Small performance patch for AVX2.
It appears the B registers are loaded, but the FMA uses the same pointers for B, rather than the registers that have been loaded?
On SPR, with AVX512/AMX disabled, I see a performance improvement for prefill and decode:
```
NEURAL_SPEED_VERBOSE=0 taskset --cpu-list 1 build/bin/run_llama -m llama2.ne.weight-int8.group-128.compute-int8.avx2.bin --seed 1 -t 1 -n 8 -c 1024 -b 1024 --memory-auto -p 'Ha ha, well, a woodchuck would certainly be able to chuck some wood! But if you’re looking for a more straightforward answer, it depends on the size of the woodchuck and the type of wood. A small woodchuck might only be able to move a few sticks of firewood at a time, while a larger one might be able to move a whole log or two. Is'
...
<before PR>
========== eval …
```

[BesTLA] AVX2: Use loaded registers of B.

---

include/common/core/base_types.hpp
include/common/core/common.hpp
include/common/core/math_general.hpp
include/common/core/memory.hpp
tests/integration/data_transformer/common.hpp
tests/utils/profiling.hpp

- Be able to build and run on both OneAPI 2024.0 and 2024.1
- Fixed some errors introduced in #119

2024.0 compatibility

---

neural_speed/convert/convert_quantized_llama.py
neural_speed/convert/convert_quantized_mistral.py
neural_speed/convert/convert_quantized_mixtral.py

[GPTQ Enhance] Fix convert_quantized model.py for dtype

---

neural_speed/core/layers/mha_dense.cpp

disable MHA_AVX2

---

docs/supported_models.md
neural_speed/models/model_utils/model_files.h
scripts/python_api_example_for_gguf.py

Model validation & Doc refine.
As [Mistral 7B v0.2 Base](https://twitter.com/MistralAILabs/status/1771670765521281370) released yesterday, this PR validated this raw pretrained model(used to train Mistral-7B-instruct-v0.2), its SFT and quantitative models.
Validated Models:
* [alpindale/Mistral-7B-v0.2-hf](https://huggingface.co/alpindale/Mistral-7B-v0.2-hf)
* [Mistral-7B-Instruct-v0.2](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2)
* [TheBloke/Mistral-7B-Instruct-v0.2-GGUF](https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF)
* [Mistral-7B-Instruct-v0.2-GPTQ](https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GPTQ)
Related PR:
Mistral-GPTQ-v0.2 PR: https://github.com/intel/neural-speed/pull/144
N/A
Extension tests. …

[Model Validation] Support Mistral-base-v0.2

---

README.md
requirements.txt
setup.py

fix https://github.com/intel/neural-speed/issues/193 and https://github.com/intel/neural-speed/issues/194
Issues: xxx

[Neural Speed] Update Setup.py

---

docs/supported_models.md
neural_speed/__init__.py
neural_speed/application/quant_model.cpp
neural_speed/convert/__init__.py
neural_speed/convert/convert_llama3.py
neural_speed/models/baichuan/baichuan_utils.cpp
neural_speed/models/llama/llama.cpp
neural_speed/models/model_utils/model_files.h

Supported llama3
N/A
Perf: -m 0 -C 0-55 m4
model.init(model_name, weight_dtype="int4", compute_dtype="int8")
model.generate(inputs, streamer=streamer, max_new_tokens=33, threads=56, ctx_size=1062, do_sample=False)
32 in 32 out
1024 in 32 out
model.init(model_name, weight_dtype="int4", compute_dtype="int8", scale_dtype="bf16")
Inference Screenshots:
FP32:
Q4_J:
N/A

[Model Enabling] llama3-8b-instruct-chat Enabling

---

neural_speed/convert/common.py

[Bug fixed] Rename tuple to Tuple to be compatible with python3.8
[Bug fixed] Rename tuple to Tuple to be compatible with python3.8
N/A
N/A

[Bug fixed] Rename tuple to Tuple to be compatible with python3.8

---

include/common/core/arch_config.hpp
include/common/core/common_types.hpp
include/common/utils/limitation.hpp
include/experimental/group/gemm/compute_policy.hpp
include/group/gemm/compute_policy.hpp
include/group/gemm/impl/default_fpu_xe.hpp
include/group/gemm/impl/default_xmx_xe.hpp
include/group/gemm/impl/unaligned_xmx_xe.hpp
include/subgroup/tile/impl/fma_xe.hpp
include/subgroup/tile/impl/load_xe.hpp
include/subgroup/tile/impl/mma_xe.hpp
include/subgroup/tile/impl/prefetch_xe.hpp
include/subgroup/tile/impl/store_xe.hpp

Add dpas attribution and refine mma, load, store attribution and related template functions
1) compilation build passed on bothe DG2 and PVC machine
2) tests/integration/gemm/int4_dequantization_bias, gemm_client_int4_dequantization_bias all test cases passed on DG2 and PVC machine

Add dpas attr, refine mma, load, store attr

---

bestla/README.md
bestla/bestla/bestla_prologue_b.h
bestla/bestla/bestla_wrapper.h
bestla/bestla/kernel_avx2.h
bestla/bestla/kernel_avx512f.h
bestla/bestla/kernel_ref.h
bestla/bestla/kernel_wrapper.h
bestla/bestla/ut/bestla_benchmark.cpp
bestla/bestla/ut/bestla_prologue_b.cpp
bestla/bestla/ut/kernel_intrin.cpp
docs/advanced_usage.md
neural_speed/core/README.md
neural_speed/models/model_utils/quant_utils.cpp

new weight_dtype: int7
LLaMa2-7B
weight_dtype=int7, group_size=128, alg=sym, scale_dtype=bf16, comp_dtype=int8:
```
Once upon a time, there existed a little girl, who liked to have adventures. She wanted to go to places and meet new people, and have fun. But her parents were very worried about her safety, so they refused to
model_print_timings:        load time =   409.37 ms
model_print_timings:      sample time =     3.48 ms /    16 runs   (    0.22 ms per token)
model_print_timings: prompt eval time =   216.56 ms /    33 tokens (    6.56 ms per token)
model_print_timings:        eval time =  1331.87 ms /    15 runs   (   88.79 ms per token)
model_print_timings:       total time =  1751.09 ms
========== eval time log of each prediction ==========
prediction   0, time: 216.56ms
prediction …
```

[BesTLA] Support int7 for kernels and models

---

README.md
bestla/README.md
bestla/bestla/bestla_prologue_b.h
bestla/bestla/bestla_wrapper.h
bestla/bestla/kernel_avx2.h
bestla/bestla/kernel_avx512f.h
bestla/bestla/kernel_ref.h
bestla/bestla/kernel_wrapper.h
bestla/bestla/ut/bestla_benchmark.cpp
bestla/bestla/ut/bestla_prologue_b.cpp
bestla/bestla/ut/bestla_ut.h
bestla/bestla/ut/kernel_intrin.cpp
docs/advanced_usage.md
neural_speed/core/README.md
neural_speed/models/model_utils/quant_utils.cpp

support new weight_dtype=int1
LLaMa2-7B
weight_dtype=int1, group_size=128, alg=sym, scale_dtype=bf16, comp_dtype=int8:
```
Once upon a time, there existed a little girl, who liked to have adventures. She wanted to go to places and meet new people, and have fun Хронологија Хронологија Хронологија Хронологија Хронологија Хронологија Хронологија Хронологија Хронологија Хронологија Хронологија Хронологија Хронологија Хронологија Хронологија Хронологија
model_print_timings:        load time =   180.49 ms
model_print_timings:      sample time =     3.36 ms /    16 runs   (    0.21 ms per token)
model_print_timings: prompt eval time =   169.91 ms /    33 tokens (    5.15 ms per token)
model_print_timings:        eval time =   293.41 ms /    15 runs   (   19.56 ms per token)
model_print_timings: …
```

[BesTLA] Support Int1 for kernels and models

---

docker/DockerFile
docker/README.md

Fixed the following:
Previous docker build command in docs didn't pass `-t` flag for the name tag. This resulted in the following error:
```
ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.
Usage:  docker buildx build [OPTIONS] PATH | URL | - 
```
Fixing this and building, I found a new issue, namely the run command trying to make `build` directory when one already exists. See stacktrace:
```
2.371 mkdir: cannot create directory ‘build’: File exists
------
DockerFile:43
--------------------
42 |     
43 | >>> RUN pip install cmake ninja psutil && \
44 | >>>     cd /neural_speed && \
45 | >>>     git submodule update --init --recursive && \
46 | >>>     mkdir build && cd build && cmake .. -G Ninja && ninja && cd .. && \
47 | >>>     pip install -r …
```

Docker fix.

---

bestla/README.md
bestla/bestla/bestla.h
bestla/bestla/bestla_device.h
bestla/bestla/bestla_gemm.h
bestla/bestla/bestla_jit.h
bestla/bestla/bestla_wrapper.h
bestla/bestla/kernel_avx512f.h
bestla/bestla/kernel_wrapper.h
bestla/bestla/ut/bestla_benchmark.cpp
bestla/bestla/ut/bestla_gemm.cpp
bestla/bestla/ut/bestla_prologue_b.cpp
bestla/bestla/ut/bestla_ut.h
bestla/bestla/ut/bestla_wrapper.cpp
bestla/bestla/ut/kernel_intrin.cpp
neural_speed/core/README.md
neural_speed/core/layers/bestla_common.hpp
neural_speed/core/layers/bestla_defs.h
neural_speed/core/layers/bestla_gemm.cpp
neural_speed/core/layers/inner_product.cpp
neural_speed/core/layers/ip_fusion_ffn.cpp
neural_speed/core/layers/ip_fusion_qkv.cpp

Add AVX512BW version of u8s8 GEMM and u8s8 GEMV.
Bring Skylake and Cannonlake to our optimized list.

[BesTLA] Add u8s8 kernel for AVX512BW

---

docs/supported_models.md
neural_speed/__init__.py
neural_speed/convert/convert_baichuan.py
neural_speed/convert/convert_llama.py
neural_speed/models/llama/llama.h
tests/model-test/calculate_percentiles.py
tests/model-test/cpp_graph_inference.sh

not
Add [tiny_llama](https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0)

Enable tiny_llama

---

CMakePresets.json
bestla/bestla/bestla_device.h
bestla/bestla/bestla_gemm.h
bestla/bestla/bestla_parallel.h
bestla/bestla/bestla_prologue_a.h
bestla/bestla/bestla_prologue_b.h
bestla/bestla/bestla_utils.h
bestla/bestla/bestla_wrapper.h
bestla/bestla/kernel_avx512f.h
bestla/bestla/kernel_ref.h
bestla/bestla/kernel_wrapper.h
bestla/bestla/ut/bestla_benchmark.cpp
bestla/bestla/ut/bestla_parallel.cpp
bestla/bestla/ut/bestla_prologue_a.cpp
bestla/bestla/ut/bestla_prologue_b.cpp
bestla/bestla/ut/bestla_ut.h
bestla/bestla/ut/bestla_wrapper.cpp
bestla/bestla/ut/kernel_wrapper.cpp
neural_speed/application/main_run.cpp
neural_speed/core/layers/bestla_defs.h
neural_speed/core/layers/bestla_gemm.cpp
neural_speed/core/layers/inner_product.cpp
neural_speed/core/layers/ip_fusion_ffn.cpp
neural_speed/core/layers/ip_fusion_qkv.cpp
neural_speed/core/layers/mha_dense_wrapper.h
neural_speed/models/model_utils/scheduler.cpp

Simplify the templates: remove some template parameters.
Use static API instead.
Reduce the compilation time and the binary size.
Compile with GCC 12.2.0 `make ne_layers`
Main branch (before #271) :
`libne_layers.so` compilation time: 10min32s  binary size: 23.6MB
PR branch:
`libne_layers.so` compilation time: 7min34s binary size: 17.0 MB

[BesTLA] Simplify the templates

---

.github/workflows/scripts/models/cpp_graph_inference.sh
tests/model-test/cpp_graph_inference.sh

[CI]add int3&int5 test

---

docs/continuous_batching.md
neural_speed/__init__.py

Issues: xxx
- fix `ret` when `ignore_prompt`
- add cont-batching benchmark throughput in doc

[Neural Speed] Fix `ret` when `ignore_prompt`

---

.github/workflows/cpp-graph-test.yml
.github/workflows/scripts/models/cpp_graph_inference.sh
neural_speed/convert/convert_quantized_qwen.py
neural_speed/convert/convert_qwen.py
neural_speed/models/qwen/qwen.cpp
neural_speed/models/qwen/qwen.h
neural_speed/models/qwen/qwen_utils.cpp

[model]Enable qwen2

---

bestla/bestla/bestla.h
bestla/bestla/bestla_device.h
bestla/bestla/bestla_gemm.h
bestla/bestla/kernel_avx2.h
bestla/bestla/kernel_avx512f.h
bestla/bestla/ut/bestla_benchmark.cpp
bestla/bestla/ut/bestla_gemm.cpp
bestla/bestla/ut/bestla_ut.h
bestla/bestla/ut/bestla_wrapper.cpp
neural_speed/core/layers/bestla_defs.h

- AMX_FP16 ISA support
- AMX_FP16 GemmCore
- Benchmark and UTs

[BesTLA] Add new ISA support: AMX_FP16

---

neural_speed/models/baichuan/baichuan.cpp
neural_speed/models/chatglm/chatglm2.cpp
scripts/huggingface.py

Issues: xxx
due to `logits_all` memory copy
```shell
ne_baichuan_q_int4_bestla_cint8_sym_sfp32_g32.bin    
|    Tasks     |Version|Filter|n-shot|  Metric  |Value |   |Stderr|
|--------------|------:|------|-----:|----------|-----:|---|-----:|
|lambada_openai|      1|none  |     0|perplexity|4.0944|±  |0.1164|
|              |       |none  |     0|acc       |0.6662|±  |0.0066|
ne_chatglm3_q_int4_bestla_cint8_sym_sfp32_g32.bin   
|    Tasks     |Version|Filter|n-shot|  Metric  |Value|   |Stderr|
|--------------|------:|------|-----:|----------|----:|---|-----:|
|lambada_openai|      1|none  |     0|perplexity|9.339|±  |0.4476|
|              |       |none  |     0|acc       |0.596|±  |0.0068| …
```

[Neural Speed] Fix Baichuan, chatGLM1&2&3 acc issue

---

docs/supported_models.md
neural_speed/__init__.py
neural_speed/convert/convert_chatglm.py
neural_speed/models/chatglm/chatglm2.h
scripts/huggingface.py
tests/model-test/cpp_graph_inference.sh

not
Enable [glm-4-9b](https://huggingface.co/THUDM/glm-4-9b)
q4j32cint8 result

[Model]enable glm4-9b

---

neural_speed/convert/convert_chatglm.py

glm4-9b q4j32 result
glm4-9b-chat q4j32 result

[Bug]fix glm4 convert error

---

include/common/core/arch_config.hpp
include/experimental/group/gemm/compute_policy.hpp
include/subgroup/tile/impl/payload_xe.hpp

As title.
Together with a fix that uses 2d load when tile_size_x/y == 1
N/A
IPEX internal tests
N/A

Xetla GRF Mode Control

---

tests/integration/fmha/fmha.cpp
tests/integration/fmha/fmha_forward.hpp
tests/integration/fmha/fmha_utils.h

Sync IPEX changes of the FMHA operator to the fmha integration test scripts.
N/A
N/A
N/A

XeTLA Sync FMHA Tests

---

include/subgroup/tile/api.hpp

As title.
N/A
IPEX internal tests
N/A

XeTLA enable BF16 tile_t Init

---

include/subgroup/tile/impl/payload_xe.hpp

As title
N/A
Internal IPEX testing pipeline
No

XeTLA Fix Global 1D Store

---

include/common/core/common.hpp
include/common/core/math_mma.hpp
include/common/core/memory.hpp
include/experimental/kernel/col_major_shuf/col_major_shuf_xe.hpp
include/group/epilogue/impl/stream_k_op_xe.hpp
include/group/global_reduction.hpp
include/subgroup/tile/common.hpp
include/subgroup/tile/impl/load_xe.hpp
include/subgroup/tile/impl/payload_xe.hpp
include/subgroup/tile/impl/prefetch_xe.hpp
include/subgroup/tile/impl/store_xe.hpp
tests/integration/gemv/int4/main.cpp
tests/integration/vector_add/int32_1d/kernel_func.hpp
tests/integration/vector_add/tf32_1d/kernel_func.hpp
tests/unit/global_atomic/kernel_func.hpp
tests/unit/global_load_store/kernel_func.hpp
tests/unit/local_load_store/kernel_func.hpp
tests/unit/math_general/kernel_func.hpp
tests/unit/named_barrier/kernel_func.hpp
tests/unit/raw_send/kernel_func.hpp

feature or bug fix or documentation or others  --   Update compiler API to 2024.2
API changed or not  --  Not
1 Update prefetch 1D API
2 Update atomic API
3 Update gather/scatter API
4 Update 1 fp16 load/store
5 Unify all length units to bytes instead of elems(common.hpp)
2D load/store/prefetch not updated, will be updated in subsequent PR
Issues: xxx

Xetla support 2024.2

---

include/common/core/memory.hpp
include/subgroup/tile/impl/load_xe.hpp
include/subgroup/tile/impl/payload_xe.hpp
tests/integration/fmha/fmha_forward.hpp
tests/integration/fmha/fmha_utils.h

Previously there is a bug with the mask load, so we have to achieve accuracy with extra overhead. This overhead will be removed in this PR.
N/A
Internal IPEX CI
`xetla` barnch
```
[ RUN      ] XeTLA/FMHATest.kUseBiasOFF_kSeqLastOFF_bs1_hn32_hs128_qlen1_klen33
[kernel time]The maximum gflops(GPU_time) is 9.90242
[ RUN      ] XeTLA/FMHATest.kUseBiasOFF_kSeqLastON_bs1_hn32_hs128_qlen1_klen33
[kernel time]The maximum gflops(GPU_time) is 10.4184
[ RUN      ] XeTLA/FMHATest.kUseBiasON_kSeqLastOFF_bs1_hn32_hs128_qlen1_klen33
[kernel time]The maximum gflops(GPU_time) is 10.3561
[ RUN      ] XeTLA/FMHATest.kUseBiasON_kSeqLastON_bs1_hn32_hs128_qlen1_klen33
[kernel time]The maximum gflops(GPU_time) is 10.5452
[ RUN      ] XeTLA/FMHATest.kUseBiasOFF_kSeqLastOFF_bs1_hn32_hs128_qlen1_kle …
```

XeTLA Zero-Passthrough
